/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumnModel;
import model.dbConect;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author YOJHAN DAVID
 */
public class pestañaMain extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public pestañaMain() {
        initComponents();

        DefaultTableModel model = new DefaultTableModel(
        new Object[][]{}, 
        new String[]{
            "Código", "Origen", "Destino", "Duración", 
            "Fecha/Hora", "Precio", "Avión", "Disponibilidad", "Estado"
        }
    ) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // Hacer que ninguna celda sea editable
        }
    };
    cargarDatos();
    tablaVuelos.setModel(model);
    
    TableColumnModel columnModel = tablaVuelos.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(80);  // Código
    columnModel.getColumn(1).setPreferredWidth(100); // Origen
    columnModel.getColumn(2).setPreferredWidth(100); // Destino
    columnModel.getColumn(3).setPreferredWidth(80);  // Duración
    columnModel.getColumn(4).setPreferredWidth(150); // Fecha/Hora
    columnModel.getColumn(5).setPreferredWidth(100); // Precio
    columnModel.getColumn(6).setPreferredWidth(120); // Avión
    columnModel.getColumn(7).setPreferredWidth(120); // Disponibilidad
    columnModel.getColumn(8).setPreferredWidth(100); // Estado

    }
    
private void cargarDatos() {
    btnActualizar.setText("ACTUALIZANDO...");
    btnActualizar.setEnabled(false);
    
    SwingUtilities.invokeLater(() -> {
        DefaultTableModel model = (DefaultTableModel) tablaVuelos.getModel();
        model.setRowCount(0); // Limpiar tabla
        
        try (Connection conn = dbConect.getConnection();
             PreparedStatement pst = conn.prepareStatement(
                 "SELECT codigo, origen, destino, duracion, fecha_hora, " +
                 "precio, avion, capacidad, pasajeros_registrados " +
                 "FROM vuelos ORDER BY fecha_hora");
             ResultSet rs = pst.executeQuery()) {
            
            while (rs.next()) {
                String codigo = rs.getString("codigo");
                String origen = rs.getString("origen");
                String destino = rs.getString("destino");
                String duracion = rs.getString("duracion");
                String fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm").format(rs.getTimestamp("fecha_hora"));
                double precio = rs.getDouble("precio");
                String avion = rs.getString("avion");
                int capacidad = rs.getInt("capacidad");
                int pasajeros = rs.getInt("pasajeros_registrados");
                
                String disponibilidad = pasajeros + "/" + capacidad;
                double porcentaje = (double) pasajeros / capacidad * 100;
                String estado = (porcentaje >= 90) ? "LLENO" : "DISPONIBLE";
                
                model.addRow(new Object[]{
                    codigo, origen, destino, duracion,
                    fechaHora, String.format("$%,.2f", precio),
                    avion, disponibilidad, estado
                });
            }
            
            tablaVuelos.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar datos:\n" + e.getMessage(),
                "Error de base de datos",
                JOptionPane.ERROR_MESSAGE);
        } finally {
            btnActualizar.setText("ACTUALIZAR");
            btnActualizar.setEnabled(true);
            tablaVuelos.revalidate();
            tablaVuelos.repaint();
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelId = new javax.swing.JTextField();
        searchBtt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        origenField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        destinoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 204));
        jTabbedPane1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        jLabel1.setText("CaribeAirlines");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("<html>CaribeAirlines es una aerolínea que representa la esencia del Caribe, conectando ciudades de Colombia con destinos nacionales e internacionales. Nos especializamos en ofrecer vuelos confiables, seguros y cómodos, destacándonos por nuestra puntualidad y atención al cliente.<p> CaribeAirlines combina tecnología avanzada con un enfoque cálido y cercano, garantizando una experiencia inolvidable en cada viaje.<html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(136, 136, 136)))
                .addGap(583, 583, 583))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("INICIO", jPanel2);

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        jLabel3.setText("CaribeAirlines");

        tablaVuelos.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 12)); // NOI18N
        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVuelos);

        jLabel2.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 12)); // NOI18N
        jLabel2.setText("Estos son los vuelos disponibles:");

        btnActualizar.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(115, 115, 115)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 368, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("VUELOS", jPanel4);

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        jLabel5.setText("CaribeAirlines");

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel6.setText("Origen");

        searchBtt.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        searchBtt.setText("BUSCAR");
        searchBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBttActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel7.setText("Ingrese la ID del vuelo que desea reservar:");

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel8.setText("Destino");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtt))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(origenField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(destinoField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtt))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(origenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RESERVAS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBttActionPerformed
     String idVuelo = labelId.getText().trim();
    
    if (idVuelo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un código de vuelo.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try (Connection conn = dbConect.getConnection();
         PreparedStatement pst = conn.prepareStatement("SELECT * FROM vuelos WHERE codigo = ?")) {
        
        pst.setString(1, idVuelo);
        
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                origenField.setText(rs.getString("origen"));
                destinoField.setText(rs.getString("destino"));
                
                int op = JOptionPane.showConfirmDialog(rootPane, 
                    "Vuelo encontrado, ¿desea reservar?", 
                    "Confirmación", 
                    JOptionPane.YES_NO_OPTION);
                
                if (op == JOptionPane.YES_OPTION) {
                    // Cambia esta línea:
                    pestañaReserva acceso = new pestañaReserva(this, idVuelo);
                    acceso.setVisible(true);
                    labelId.setText("");
                } else {
                    origenField.setText("");
                    destinoField.setText("");
                    labelId.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se encontró el vuelo con código: " + idVuelo, 
                    "No encontrado", 
                    JOptionPane.WARNING_MESSAGE);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error al buscar vuelo: " + e.getMessage(), 
            "Error de base de datos", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_searchBttActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:    btnActualizar.setEnabled(false);
        cargarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new pestañaMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JTextField destinoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField labelId;
    private javax.swing.JTextField origenField;
    private javax.swing.JButton searchBtt;
    private javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables

    void refrescarTablaVuelos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 
}
